name: Lua

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download StyLua
        run: |
          curl -L https://github.com/JohnnyMorganz/StyLua/releases/download/v2.0.2/stylua-linux-x86_64.zip -o stylua.zip
          unzip stylua.zip
          chmod +x stylua

      - name: Run StyLua
        run: ./stylua --check . --indent-type spaces

      - name: Luacheck
        uses: lunarmodules/luacheck@v1
        with:
          args: . --globals vim
